app/Http/routes.php
<?php

use Vinder\Libraries\Reports\Report;
use Vinder\Libraries\Campaing;

use Vinder\Entities\Location;
use Vinder\Libraries\Sms\SendSMS;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/***** Auth *****/
Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

/** App **/
Route::group(['middleware' => ['auth']], function()
{
	Route::get('/', ['as' => 'modules', 'uses' => 'DashboardController@index']);

	Route::group(['prefix' => 'system', 'middleware' => 'module:system', 'namespace' => 'System'], function() 
	{
		Route::get('/', ['as' => 'system', 'uses' => 'SystemController@getindex']);
		Route::get('logs', ['as' => 'system.logs', 'uses' => '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index']);
		Route::resource('users', 'UsersController');
		Route::resource('user-types', 'UserTypesController');
		Route::resource('modules', 'ModulesController');
		Route::resource('locations', 'LocationsController');
		Route::resource('polling-stations', 'PollingStationsController');
	});
		
	Route::group(['prefix' => 'database', 'namespace' => 'Database', 'middleware' => 'module:database'], function() 
	{
		Route::get('/', ['as' => 'database', 'uses' => 'DataBaseController@index']);

		Route::group(['middleware' => 'module:delete-voters'], function() { 
			Route::post('voters/delete/{id}', ['as' => 'database.voters.destroy', 'uses' => 'VotersController@destroy']);
		});

		Route::group(['middleware' => 'module:voters'], function() {
			Route::get('voters', ['as' => 'database.voters.index', 'uses' => 'VotersController@index']);
			Route::post('voters/redirect', ['as' => 'database.voters.redirect', 'uses' => 'VotersController@redirect']);
			Route::get('voters/search', ['as' => 'database.voters.search', 'uses' => 'VotersController@search']);
			Route::get('voters/find-name/{doc}', ['as' => 'database.voters.find-name', 'uses' => 'VotersController@findName']);
			Route::get('voters/find-polling-station/{doc}', ['as' => 'database.voters.find-polling-station', 'uses' => 'VotersController@findPollingStation']);
			Route::get('voters/diaries/{doc}', ['as' => 'database.voters.diaries', 'uses' => 'VotersController@diaries']);
			
			Route::get('voters/{id}/add-to-team/{diary?}', ['as' => 'database.voters.add-to-team', 'uses' => 'VotersController@addToTeam', 'middleware' => 'module:add-to-team-voters']);
			Route::get('voters/{doc}/{diary?}', ['as' => 'database.voters.create', 'uses' => 'VotersController@create']);
			Route::post('voters/{doc}/{diary?}', ['as' => 'database.voters.store', 'uses' => 'VotersController@store']);
		});

		Route::group(['middleware' => 'module:team'], function() {
			Route::get('team', ['as' => 'database.team.index', 'uses' => 'ColaboratorsController@index']);
			Route::post('team/redirect', ['as' => 'database.team.redirect', 'uses' => 'ColaboratorsController@redirect']);
			Route::get('team/{doc}/remove/{diary?}', ['as' => 'database.team.remove', 'uses' => 'ColaboratorsController@remove']);				
			Route::get('team/{doc}/{diary?}', ['as' => 'database.team.create', 'uses' => 'ColaboratorsController@create']);
			Route::post('team/{doc}/{diary?}', ['as' => 'database.team.store', 'uses' => 'ColaboratorsController@store']);
		});

		Route::group(['middleware' => 'module:roles'], function() {
			Route::resource('roles', 'RolesController',  ['only' => ['index', 'edit', 'update', 'store', 'destroy']]);
		});
	});

	Route::group(['namespace' => 'Secondary'], function() {
		Route::group(['middleware' => 'module:reports'], function() {
			Route::controller('reports', 'ReportsController', [
				'getIndex' 								=> 'reports.index',

				'getPeople' 							=> 'reports.people',
				'getDelegates'							=> 'reports.delegates',
				'getPeopleWithBirthdayCurrentMonth' 	=> 'reports.people-with-birthday-current-month',
				'getPeopleWithoutPollingStation' 		=> 'reports.people-without-polling-station',

				'getPeopleOfLocations' 					=> 'reports.people-of-locations',
				'getPeopleOfPollingStations' 			=> 'reports.people-of-polling-stations',
				'getPeopleOfPollingStationsDayD' 		=> 'reports.people-of-polling-stations-day-d',
				'getPeopleOfCommunities' 				=> 'reports.people-of-communities',
				'getPeopleOfOccupations' 				=> 'reports.people-of-occupations',

				'getTeamWithVoters' 					=> 'reports.team-with-voters',
				'getRecursiveTeam' 						=> 'reports.recursive-team',
				'getRecursiveTeamVoters' 				=> 'reports.recursive-team-voters',
				'getTeam' 								=> 'reports.team',

				'getTeamOfRoles'						=> 'reports.team-of-roles',

				'getPlans' 								=> 'reports.plans',
				'getPlansTeam' 							=> 'reports.plans-team',
				
				'getBlankTemplate' 						=> 'reports.blank-template',
				
				'getUsers'								=> 'reports.users',
				'getVoterPolls'							=> 'reports.voter-polls'
			]);
		});
			
		Route::group(['prefix' => 'statistics', 'middleware' => 'module:statistics'], function() 
		{
			Route::controller('/', 'StatisticsController', [
				'getIndex'							=> 'statistics.index',
				'getBars'							=> 'statistics.bars',
				'getVotersOfPollingStations'		=> 'statistics.voters-of-polling-stations',
				'getVotersOfPollingStationsDayD'	=> 'statistics.voters-of-polling-stations-day-d',
				'getVotersOfLocations' 				=> 'statistics.voters-of-locations'
			]);		
		});

		Route::group(['middleware' => 'module:diary'], function() 
		{
			Route::get('diary-json', ['as' => 'diary.json', 'uses' => 'DiaryController@json']);
			Route::get('diary-print', ['as' => 'diary.print', 'uses' => 'DiaryController@printDiary']);
			Route::resource('diary', 'DiaryController');
			
			Route::get('diary/{diary}/people', ['as' => 'diary.people.index', 'uses' => 'DiaryPeopleController@index']);
			Route::post('diary/{diary}/people/add-masive', ['as' => 'diary.people.add-masive', 'uses' => 'DiaryPeopleController@addMasive']);

			Route::post('diary/{diary}/people/{id}/remove', ['as' => 'diary.people.remove', 'uses' => 'DiaryPeopleController@remove']);


		});

		Route::group(['prefix' => 'logistic', 'middleware' => 'module:logistic'], function(){
			Route::get('/', ['as' => 'logistic', 'uses' => 'LogisticController@getindex']);
		});

		Route::group(['prefix' => 'advertising', 'middleware' => 'module:advertising'], function(){
			Route::get('/', ['as' => 'advertising', 'uses' => 'AdvertisingController@getindex']);
		});
	});
	
	Route::group(['namespace' => 'Extra'], function() {
		
		/* Envío masivo de Mensajes de texto */
		Route::group(['middleware' => 'module:sms'], function() {
			Route::controller('sms', 'SmsController', [
				'getIndex' 				=> 'sms.index',
				'postSend' 				=> 'sms.send',		
			]);
		});
		/* Fin Modulo Envío masivo de Mensajes de texto */

		Route::group(['middleware' => 'module:polls'], function() {
			Route::resource('polls', 'PollsController');
			Route::resource('polls.questions', 'PollsQuestionsController');	
			Route::get('polls/{polls}/stats', ['as' => 'polls.stats', 'uses' => 'PollsController@stats']);
			Route::get('polls/{polls}/stats/json', ['as' => 'polls.stats.json', 'uses' => 'PollsController@statsJson']);
			Route::delete('answers/{id}/delete', ['as' => 'answers.destroy', 'uses' => 'PollsQuestionsController@answersDestroy']);

			Route::get('polls/{polls}/voters/options', ['as' => 'polls.voters.options', 'uses' => 'PollsVotersController@options']);
			Route::post('polls/{polls}/voters/options', ['as' => 'polls.voters.options.store', 'uses' => 'PollsVotersController@postOptions']);
			Route::resource('polls.voters', 'PollsVotersController');
		});
	});
	
});

app/Http/Controllers/System/LocationsController.php
<?php namespace Vinder\Http\Controllers\System;

use Illuminate\Routing\Route;
use Illuminate\Http\Request;

use Vinder\Http\Controllers\Controller;
use Vinder\Entities\Location;

use Vinder\Http\Requests\Location\CreateRequest;
use Vinder\Http\Requests\Location\EditRequest;

class LocationsController extends Controller {

	private $location;

	public function __construct() 
	{
		$this->beforeFilter('@newLocation', ['only' => ['create', 'store']]);
		$this->beforeFilter('@findLocation', ['only' => ['edit', 'update']]);
	}

	/**
	 * A new instance of location
	 *
	 */
	public function newLocation()
	{
		$this->location = new Location;
	}

	/**
	 * Find a specific location
	 *
	 */
	public function findLocation(Route $route)
	{
		$this->location = Location::findOrFail($route->getParameter('locations'));
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$locations = Location::with('type', 'superiorLocation')->get();	

		return view('dashboard.pages.system.locations.lists', compact('locations'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$form_data = ['route' => 'system.locations.store', 'method' => 'POST'];
		
		return view('dashboard.pages.system.locations.form', compact('form_data'))
			->with('location', $this->location);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateRequest $request)
	{
        $this->location->fill($request->all());
        $this->location->save();

		return redirect()->route('system.locations.index');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$form_data = ['route' => ['system.locations.update', $this->location->id], 'method' => 'PUT'];
		
		return view('dashboard.pages.system.locations.form', compact('form_data'))
			->with('location', $this->location);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, EditRequest $request)
	{
        $this->location->fill($request->all());
        $this->location->save();

		return redirect()->route('system.locations.index');
	}
}

app/Http/Controllers/System/ModulesController.php
<?php namespace Vinder\Http\Controllers\System;

use Vinder\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;

use Vinder\Entities\Module;

use Vinder\Http\Requests\Module\CreateRequest;
use Vinder\Http\Requests\Module\EditRequest;

class ModulesController extends Controller {

	private $module;

	public function __construct() 
	{
		$this->beforeFilter('@newModule', ['only' => ['create', 'store']]);
		$this->beforeFilter('@findModule', ['only' => ['show', 'edit', 'update', 'destroy']]);
	}

	public function newModule()
	{
	 	$this->module = new Module;
	} 

	public function findModule(Route $route)
	{
	 	$this->module = Module::findOrFail($route->getParameter('modules'));
	} 

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$modules = Module::all();

		return view('dashboard.pages.system.modules.lists', compact('modules'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$form_data = ['route' => 'system.modules.store', 'method' => 'POST'];

		return view('dashboard.pages.system.modules.form', compact('form_data'))
			->with('module', $this->module);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateRequest $request)
	{
        $this->module->fillAndSave($request->all());
		
		return redirect()->route('system.modules.index');
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		return view('dashboard.pages.system.modules.show', compact('module'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$form_data = ['route' => ['system.modules.update', $this->module->id], 'method' => 'PUT'];

		return view('dashboard.pages.system.modules.form', compact('form_data'))
			->with('module', $this->module);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, EditRequest $request)
	{
        $this->module->fillAndSave($request->all());
       
		return redirect()->route('system.modules.index');
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
    {
        $this->module->delete();

        if (Request::ajax())
        {
            return Response::json(array (
                'success' => true,
                'msg'     => 'Modulo "' . $this->module->name . '" eliminado',
                'id'      => $this->module->id
            ));
        }
        else
        {
            return redirect()->route('system.modules.index');
        }
	}


}

app/Http/Controllers/System/PollingStationsController.php
<?php namespace Vinder\Http\Controllers\System;

use Illuminate\Routing\Route;
use Illuminate\Http\Request;

use Vinder\Http\Controllers\Controller;
use Vinder\Entities\PollingStation;
use Vinder\Libraries\ReportsUtilities;

use Vinder\Http\Requests\PollingStation\CreateRequest;
use Vinder\Http\Requests\PollingStation\EditRequest;

class PollingStationsController extends Controller {

	private $polling_station;

	public function __construct() 
	{
		$this->beforeFilter('@newPollingStation', ['only' => ['create', 'store']]);
		$this->beforeFilter('@findPollingStation', ['only' => ['edit', 'update']]);
	}

	/**
	 * A new instance of polling_station
	 *
	 */
	public function newPollingStation()
	{
		$this->polling_station = new PollingStation;
	}

	/**
	 * Find a specific polling_station
	 *
	 */
	public function findPollingStation(Route $route)
	{
		$this->polling_station = PollingStation::findOrFail($route->getParameter('polling_stations'));
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$polling_stations = PollingStation::with('location')->get();
		return view('dashboard.pages.system.polling_stations.lists', compact('polling_stations'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$form_data = ['route' => 'system.polling-stations.store', 'method' => 'POST'];
		
		return view('dashboard.pages.system.polling_stations.form', compact('form_data'))
			->with('polling_station', $this->polling_station);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateRequest $request)
	{
        $this->polling_station->fill($request->all());
        $this->polling_station->save();

		return redirect()->route('system.polling-stations.index');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$form_data = ['route' => ['system.polling-stations.update', $this->polling_station->id], 'method' => 'PUT'];
		
		return view('dashboard.pages.system.polling_stations.form', compact('form_data'))
			->with('polling_station', $this->polling_station);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, EditRequest $request)
	{
        $this->polling_station->fill($request->all());
        $this->polling_station->save();

		return redirect()->route('system.polling-stations.index');
	}
}

app/Http/Controllers/System/SystemController.php
<?php namespace Vinder\Http\Controllers\System;

use Vinder\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SystemController extends Controller {

	public function getIndex()
	{
		return view('dashboard.pages.system.hello');
	}

}

resources/views/dashboard/pages/system/user_types/form.blade.php
@extends('dashboard.pages.layout')
@section('title_page')
    @if($user_type->exists) Tipo de usuario: {{ $user_type->name }} @else Nuevo tipo de usuario @endif
@endsection
@section('breadcrumbs') {!! Breadcrumbs::render('user-types.create', $user_type) !!}
@endsection
@section('content_body_page')
	<div class="row">
	    <div class="col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
	        <div class="block">
	            <div class="block-title">
	                <h2>Datos del tipo de usuario</h2>
	            </div>

                {!! Form::model($user_type, $form_data + array('id' => 'form-usertypes', 'class' => 'form-horizontal form-bordered'))!!}

                    {!! Field::text('name', null, ['template' => 'horizontal', 'placeholder' => 'Nombre']) !!}

                    {!! Field::text('description', null, ['template' => 'horizontal', 'placeholder' => 'Descripción']) !!}

                    {!! Field::checkbox('can_view_all', 1, ['template' => 'switche-large']) !!}

                    {!! Field::select('modules[]', $modules, $user_type->module_ids, ['template' => 'horizontal', 'data-placeholder' => 'Seleccione los módulos con acceso', 'multiple']) !!}
                                
	                <div class="form-group form-actions">
	                    <div class="col-md-8 col-md-offset-4">
                            <button type="submit" class="btn btn-effect-ripple btn-primary">Guardar</button>
	                    </div>
	                </div>

	            {!! Form::close()!!}

	        </div>
	    </div>
	</div>
@endsection
@section('js_aditional')
	{!! Html::script('assets/js/pages/formUserTypes.js') !!}
	<!-- Load and execute javascript code used only in this page -->
    <script> $(function (){ FormUserTypes.init(); });</script>
@endsection

resources/views/dashboard/pages/system/user_types/lists.blade.php
@extends('dashboard.pages.layout')
@section('class_icon_page') fa fa-users @endsection
@section('title_page') Tipos de usuario @endsection
@section('breadcrumbs') {!! Breadcrumbs::render('user-types') !!} @endsection
@section('content_body_page')
    <div class="row" id="title_page" style="margin-bottom: 10px;">
    	<div class="col-md-12">
            <a href="{{ route('system.user-types.create')}}" class="btn btn-primary"><i class="fa fa-user"></i> Nuevo tipo de usuario</a>
        </div>
    </div>
    <div class="block full">
        <div class="table-responsive">
            <table id="datatable" class="table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th title="Nombre">Nombre</th>
                        <th title="Modulos">Modulos</th>
                        <th title="Puede ver todos los registros en sus modulos con permiso">
                            <i class="fa fa-eye"></i>
                        </th>
                        <th class="text-center" style="width: 115px;"><i class="fa fa-flash"></i></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($user_types as $user_type)
                        <tr>
                            <td>{{ $user_type->name }}</td>
                            <td>
                                @foreach($user_type->modules as $module)
                                    <span class="label label-info"> {{ $module->description }} </span> &nbsp;
                                @endforeach
                            </td>
                            <td class="text-center"> {{ $user_type->can_view_all_text }} </td>
                            <td class="text-center">
                                @if(! $user_type->system)
                                    <a href="{{ route('system.user-types.edit', $user_type->id)}}" data-toggle="tooltip" title="Editar tipo de usuario" class="btn btn-effect-ripple btn-warning">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                    <a href="#" data-id="{{ $user_type->id }}" id="btn-delete-{{ $user_type->id}}" onclick="deleteModel('btn-delete-{{ $user_type->id!!}')"  data-toggle="tooltip" title="Borrar tipo de usuario" class="btn btn-effect-ripple btn-danger">
                                        <i class="fa fa-times"></i>
                                    </a>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Block -->
    {!! Form::open(array('route' => array('system.user-types.destroy', 'ID') , 'method' => 'DELETE', 'role' => 'form', 'id' => 'form-delete'))!!}
@endsection
@section('js_aditional')
	<!-- Load and execute javascript code used only in this page -->
    {!! Html::script('assets/js/lists.js') !!}
	{!! Html::script('assets/js/pages/uiTables.js') !!}
    <script>$(function(){ UiTables.init(); });</script>
@endsection